version: '3.4'

services:
  basketdb:
    image: redis:alpine

  catalogdb:
    image: mongo

  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
  
  portainer:
    image: portainer/portainer-ce

  kanbersky.hc.basket.api:
    image: ${DOCKER_REGISTRY-}kanberskyhcbasketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Kanbersky.HC.Basket.Api/Dockerfile

  kanbersky.hc.catalog.api:
    image: ${DOCKER_REGISTRY-}kanberskyhccatalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Kanbersky.HC.Catalog.Api/Dockerfile

  kanbersky.hc.ordering.api:
    image: ${DOCKER_REGISTRY-}kanberskyhcorderingapi
    build:
      context: .
      dockerfile: src/Services/Ordering/Kanbersky.HC.Ordering.Api/Dockerfile

volumes:
    elasticsearch-data:
    mongo_data:
    portainer_data: