version: '3.4'

services:
  basketdb:
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379" 

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db 
  
  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "ttt12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data 

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  portainer:
    container_name: portainer
    restart: always
    ports:
        - "8010:8000"
        - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  kanbersky.hc.basket.api:
    container_name: kanbersky.hc.basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "ElasticsearchSettings:Url=http://elasticsearch"
    ports:
      - "8001:80"
    depends_on:
      - basketdb
      
  kanbersky.hc.catalog.api:
    container_name: kanbersky.hc.catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoDBSettings:ConnectionStrings=mongodb://catalogdb:27017"
      - "ElasticsearchSettings:Url=http://elasticsearch"
    ports:
      - "8002:80"
    depends_on:
      - catalogdb

  kanbersky.hc.ordering.api:
    container_name: kanbersky.hc.ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OrderDbSettings:ConnectionStrings=Server=orderdb;Database=OrderDb;User Id=sa;Password=ttt12345678"  
      - "ElasticsearchSettings:Url=http://elasticsearch"
    ports:
      - "8003:80"
    depends_on:
      - orderdb

  kanbersky.hc.bff.api:
    container_name: kanbersky.hc.bff.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://kanbersky.hc.catalog.api"
      - "ApiSettings:BasketUrl=http://kanbersky.hc.basket.api"
      - "ApiSettings:OrderingUrl=http://kanbersky.hc.ordering.api"
      - "ElasticsearchSettings:Url=http://elasticsearch"
    depends_on:
      - kanbersky.hc.basket.api
      - kanbersky.hc.catalog.api
      - kanbersky.hc.ordering.api
    ports:
      - "8048:80" 
