version: '3.4'

services:
  basketdb:
    image: redis:alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1

  kanbersky.hc.basket.api:
    image: ${DOCKER_REGISTRY-}kanberskyhcbasketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Kanbersky.HC.Basket.Api/Dockerfile

volumes:
    elasticsearch-data: